### ISSUE TITLE
Check for existing participant and don't overwrite with defaults in RegistrationEvent

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.remoteevent#27]
This overwrites existing participant data because there is no check for an existing participant, in case an ID was given with the submission.

https://github.com/systopia/de.systopia.remoteevent/blob/9919db98d21e34501204821ca5b5749b925c28b3/Civi/RemoteParticipant/Event/RegistrationEvent.php#L57-L65

*(possible) systopia-reference: 18952*

**Comment by bjendres** [comment]
@jensschuppe could you verify that the last commit fixes your issue?

**Comment by jensschuppe** [comment]
I still didn't get to testing this, but it definitely should fix the issue. However, the code in `\Civi\RemoteParticipant\Event\RegistrationEvent::getParticipantID()` doesn't check whether a participant with a given ID really exists, it just relies on the `id` inside the `$this->participant` array.

Also, in case of an ID being submitted, `$this->participant_id` is not updated in the constructor. So I'd suggest (in the constructor)
* checking whether an ID was passed,
* checking whether a participant with that ID exists,
* updating `$this->participant_id` accordingly

**Comment by jensschuppe** [comment]
@bjendres Would you be able to address the issues before version 1.1.0 will be released?

**Comment by jensschuppe** [comment]
After scanning the relevant code again, I'm quite sure that my concerns are irrelevant. This issue is only relevant for *CiviRemote Event* profile forms that include the `role_id` as a submitted value, so the fix in 56ae3cacbc81e5fad5011643ff3e2964800e965d makes a lot of sense. I'll just merge it for the `1.2.x` branch.
