### ISSUE TITLE
RemoteEvent configuration not copied to event clone

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.remoteevent#28]
It seems that sometimes (yet unclear when) the remote event configuration in the ``event_remote_registration`` table is _not_ copied from an event template to a new event instance.

**Comment by jensschuppe** [comment]
This has been released with version 1.0-beta11.

**Comment by bjendres** [comment]
We've changed the implementation of the ``RemoteEvent.spawn`` function to a combination of 

1. using the APIv4 ``Event.getsingle`` call to create the event with all data
1. supplying the ``template_id`` in that APIv4 call to trigger the BAO::copy function.

**Comment by jensschuppe** [comment]
@bjendres I commented on 764e3ff7b871561152b669708ee97bbd52050f5b regarding APIv4 usage. Maybe the adjustments should've been a PR for reviews …

**Comment by bjendres** [comment]
I've changed it to the ``->single()`` method, since it would be ok to throw an execption if the template_id didn't exist. 

Since the query is for a ``id`` value, this should be fine unless it's empty - in which case the exception is correct.

@jensschuppe are you sure this is compatible to ``->getArrayCopy()[0]`` or would somebody have to re-test this?

**Comment by bjendres** [comment]
@jensschuppe if you're happy with this, i'll merge the rest of the code to ``master``, too. Sorry this is a little messy and not a proper individual PR. It's rather a couple of bug fixes to the original [#28].

**Comment by jensschuppe** [comment]
> I've changed it to the `->single()` method, since it would be ok to throw an execption if the template_id didn't exist.

Well, the [implementation](https://github.com/civicrm/civicrm-core/blob/4eaccf28fe5fc0b8805a488be9a79a126d9206a7/CRM/Utils/Array.php#L1214-L1241) does an iteration on the iterable result object, effectively returning the first iteration, which is an array for APIv4 result objects.

Actually, `->getArrayCopy()[0]` might not always yield correct results (when the result has associative indices), or even fail with an `Undefined offset "0"` warning.

Testing it still wouldn't hurt - I just looked at the code …

**Comment by jensschuppe** [comment]
I merged that branch for `1.2` alpha, so this will eventually get enough testing.
